# Generated by Django 5.0.6 on 2024-06-27 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("VendorNo", models.AutoField(primary_key=True, serialize=False)),
                ("VendorName", models.CharField(max_length=500)),
                ("Email", models.EmailField(max_length=254)),
                ("Territory", models.CharField(max_length=255)),
                ("IaAlertDays", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                ("PONO", models.AutoField(primary_key=True, serialize=False)),
                ("ShipDate", models.DateField()),
                ("Customer", models.CharField(max_length=255)),
                ("IaSubmissionDate", models.DateField()),
                ("InspectionDate", models.DateField()),
                (
                    "VendorNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_main.vendor",
                    ),
                ),
            ],
        ),
    ]
