# Generated by Django 5.0.6 on 2024-06-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="PONO",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="VendorNo",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
