# Generated by Django 5.0.6 on 2024-06-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0002_alter_purchaseorder_pono_alter_vendor_vendorno"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="test",
            field=models.TextField(null=True),
        ),
    ]
