# Generated by Django 5.0.6 on 2024-06-28 11:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0005_details"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Details",
        ),
    ]
