# Generated by Django 5.0.6 on 2024-07-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0006_document_doctype_document_pono"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="Doc",
            field=models.FileField(blank=True, null=True, upload_to="files"),
        ),
    ]
