# Generated by Django 5.0.6 on 2024-06-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0006_delete_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="Details",
            fields=[
                (
                    "DocNo",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("Doc", models.FileField(default=None, upload_to="app_main/")),
            ],
        ),
    ]
