# Generated by Django 5.0.6 on 2024-06-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0007_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="details",
            name="Doc",
            field=models.FileField(blank=True, null=True, upload_to="app_main/"),
        ),
    ]
