# Generated by Django 5.0.6 on 2024-07-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0007_alter_document_doc"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="Alerts",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="InspectionDateProposed",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="Status",
            field=models.CharField(default="Inspection date to be submitted"),
        ),
        migrations.AddField(
            model_name="vendor",
            name="Email2",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="Email3",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="Email4",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="Email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="IaAlertDays",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="Territory",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
