# Generated by Django 5.0.6 on 2024-07-01 04:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0008_alter_details_doc"),
    ]

    operations = [
        migrations.RenameField(
            model_name="details",
            old_name="DocNo",
            new_name="DocName",
        ),
    ]
