# Generated by Django 5.0.6 on 2024-07-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0009_remove_vendor_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="Email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
