# Generated by Django 5.0.6 on 2024-07-03 10:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0012_vendor_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendor",
            name="Password",
        ),
    ]
