# Generated by Django 5.0.6 on 2024-07-03 10:12

from django.db import migrations

def set_default_passwords(apps, schema_editor):
    Vendor = apps.get_model('app_main', 'Vendor')
    for vendor in Vendor.objects.all():
        if not vendor.Password:
            vendor.Password = vendor.VendorNo
            vendor.save()

class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0014_vendor_password"),
    ]

    operations = [
        migrations.RunPython(set_default_passwords),
    ]
