# Generated by Django 5.0.6 on 2024-07-05 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0015_set_default_passwords"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="DocName",
        ),
    ]
