# Generated by Django 5.0.6 on 2024-07-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0016_remove_document_docname"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="DocName",
            field=models.TextField(max_length=255, null=True),
        ),
    ]
