# Generated by Django 5.0.6 on 2024-07-09 05:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0018_users"),
    ]

    operations = [
        migrations.DeleteModel(
            name="users",
        ),
    ]
