# Generated by Django 5.0.6 on 2024-07-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0019_delete_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="users",
            fields=[
                (
                    "username",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("user", "User")],
                        default="user",
                        max_length=5,
                    ),
                ),
                ("password", models.CharField(max_length=500)),
            ],
        ),
    ]
