# Generated by Django 5.0.6 on 2024-07-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0021_document_vendorno"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="id",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
