# Generated by Django 5.0.6 on 2024-07-09 07:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0022_users_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="id",
        ),
    ]
