# Generated by Django 5.0.6 on 2024-07-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0024_purchaseorder_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="Convention",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="Date",
            field=models.DateField(null=True),
        ),
    ]
