# Generated by Django 5.0.6 on 2024-07-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0025_document_convention_document_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="Date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
