# Generated by Django 5.0.6 on 2024-07-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0027_purchaseorder_vendoralerts"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
