# Generated by Django 5.0.6 on 2024-07-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0028_users_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("user", "User"), ("qa", "Qa")],
                default="user",
                max_length=5,
            ),
        ),
    ]
